enum Token{
        SPACE = 256,
        ENDF = 1000, 
        ENDL,
        MAIN_SIG, 
        FLBRACK, 
        FRBRACK, 
        CLBRACK, 
        CRBRACK, 
        INCLUDE_SIG,
        ILBRACK,
        IRBRACK,
        DOT_H, 
        ID,
        RETURN,
        NUM,
        STR,
        DOT_COMMA, 
        COMMA, 
        TYPE, 
        EQUALS,
        SCANF, 
        PRINTF, 
        IF, 
        ELSE, 
        MUL, 
        DIV, 
        RDIV, 
        PLUS, 
        MINUS, 
        LOG_LEFT, 
        LOG_RIGHT, 
        LOG_E_LEFT, 
        LOG_E_RIGHT, 
        LOG_EQUAL, 
        LOG_NOT_EQUAL
    };